// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwA0Ehj68caGopwr_UBawxra4YU4qXT5Q',
    appId: '1:91175147280:web:94956a02f6350584a9f795',
    messagingSenderId: '91175147280',
    projectId: 'gemini-pay-fb7ad',
    authDomain: 'gemini-pay-fb7ad.firebaseapp.com',
    storageBucket: 'gemini-pay-fb7ad.appspot.com',
    measurementId: 'G-PZ1F98VLK9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_DadAUwP6jweNXaV-PDwelAgH87clAEU',
    appId: '1:91175147280:android:1ce9544c5b0b5320a9f795',
    messagingSenderId: '91175147280',
    projectId: 'gemini-pay-fb7ad',
    storageBucket: 'gemini-pay-fb7ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMK2uBnajDBu-XLbbDh-iw0YlBo4Hoqak',
    appId: '1:91175147280:ios:dce6b5c34a1b7cd2a9f795',
    messagingSenderId: '91175147280',
    projectId: 'gemini-pay-fb7ad',
    storageBucket: 'gemini-pay-fb7ad.appspot.com',
    iosBundleId: 'com.albus.app',
  );

}